### ISSUE TITLE
Add member background_color

### ISSUE THREAD

**Issue by BorhnN** [tomitm/appmanifest#12]
from MSDN:
Defines the expected background color for the web application. This value repeats what is already available in the application stylesheet, but can be used by browsers to draw the background color of a web application when the manifest is available before the stylesheet has loaded. This creates a smooth transition between launching the web application and loading the application's content.

this guy has it. https://app-manifest.firebaseapp.com/

**Comment by tomitm** [comment]
@BorhnN This is already available, just collapsed under the theme/icons section.
